### ISSUE TITLE
REFACTOR: 유저 정보 전송, 친구 api 구현

### ISSUE THREAD

**Issue by bianbbc87** [mooco-renew/mooco-RN#24]
## 🔨 Description

- 유저 정보 전송, 친구 api 구현

## ✅ Tasks

- [ ] api 폴더 분리 후 연결
- [ ] 친구 목록, 유저 정보 전송 style 변경
- [ ] kakao login 시 경로 변경

## ▪ Etc
