### ISSUE TITLE
STYLE: 시작-회원가입-로그인 스타일 refactor

### ISSUE THREAD

**Issue by bianbbc87** [mooco-renew/mooco-RN#9]
## 🔨 Description

- 온보딩-회원가입-로그인 스타일 리팩토링

## ✅ Tasks

- [ ] 배경색 변경
- [ ] 일반 회원가입, 로그인 삭제
- [ ] 온보딩 스타일 변경
- [ ] 페이지 라우팅 구조 변경

## ▪ Etc

**Comment by bianbbc87** [comment]
figma와 맞춰서 디자인 수정 필요
- 이미지 다운로드 후 디자인 재수정
